### PR TITLE
[feat] add us cities ui components

### PR DESCRIPTION
**Pull request by polina-munoz**
## Summary of Changes
- Add drop down menu that is pre-populated with available US cities that have trending data using `api/us/cities`
- Add search/filter feature to drop down.
- Add ability to see top trends for a state after selecting state from drop down using `/api/us/states/:statename/weeklyvolume`
- Ran `grunt jshint` to clean up missing semi colons.

Added following new Angular libraries:
- angular-sanitize
- ui-select
- bootstrap (haven't used this yet)
- angular bootstrap (haven't used this yet)

Rough gif for your viewing pleasure (will work on my gif making skills);
http://g.recordit.co/ykcG5gAVke.gif

### CODE REVIEW

**Comment by polina-munoz** [comment]
@gratnam if you're feeling better and still want to learn what we're doing, you could help read/comment on pull requests. @SimonDing87's been doing an awesome job so far :)

**Comment by bgoodfliesh** [comment]
Everything looks good to me, jshint really likes those semicolons huh?

**Comment by SimonDing87** [comment]
:+1:  lol semicolons.  Looks good!  Looking forward to explore what you've added!

**Comment by polina-munoz** [comment]
thanks guys! merging

**Pull request merged**
