### PR TITLE
Prepare MMVP for Deployment

### PR DESCRIPTION
**Pull request by polina-munoz**
## Summary of changes
- Set up one call to Twitter's `GET trends/available` endpoint to return one object of countries
- Added `/api` Express route
- Added functionality to Angular to call `/api` route and return object of countries
- Added Heroku configuration variables

### CODE REVIEW

**Comment by gratnam** [comment]
looks good

**Comment by bgoodfliesh** [comment]
👍

**Comment by SimonDing87** [comment]
some missing semi-colons in the controller files, but looks fine

**Comment by polina-munoz** [comment]
lol it's okay @SimonDing87 I will try to get better about catching missing semi colons :)

**Comment by polina-munoz** [comment]
Sweet, merging to master

**Pull request merged**
